version: '3.0'

services:
  rasa:
    image: rasa/rasa:latest-full
    container_name: rasa
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "E:/School/Rasa:/app/"
    command:
    - run

  action_server:
    image: rasa/rasa-sdk:latest
    container_name: action_server
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "E:/School/Rasa/actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    container_name: duckling
    networks: ['rasa-network']
    ports:
    - "8000:8000"

networks: {rasa-network: {}}