version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5005:5005
    volumes:
      - E:/School/Rasa/:/app
    command:
      - run
  duckling:
    image: rasa/duckling:latest
    ports:
      - 8000:8000
  app:
    image: nguyenhuy17798/rasa_actions:init
    expose: [5055]
